<a href="https://colab.research.google.com/github/PhatDiaz/ai-engineer-roadmap/blob/main/day05_numpy_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Task 1 — Vector & Matrix**

**Vector**

In [ ]:
# 1 vector có thể hiểu đơn giản là array 1 chiều

import numpy as np

v = np.array([1, 2, 3])
print(v.shape)

(3,)


**Matrix**

In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix.shape)

(2, 3)


# **Task 2 — Element-wise Operations**

In [ ]:
# Cho
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Cộng từng phần tử tương ứng của 2 array
print(a + b)

# Trừ từng phần tử tương ứng của 2 array
print(a - b)

# Nhân từng phần tử tương ứng của 2 array
print(a * b)

# Chia từng phần tử tương ứng của 2 array
print(a / b)

# Bình phương từng phần tử của array A
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


# **Task 3 — Dot Product**
# **(Tích vô hướng)**

In [ ]:
# Cho
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Tính: 1×4 + 2×5 + 3×6
print(np.dot(a, b))

# Có thể viết a @ b
print(a @ b)

32
32


**Matrix multiplication**

In [ ]:
# Cho
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print(A @ B)

[[19 22]
 [43 50]]


**Vì sao dot product quan trọng trong AI?**



Sau này Neural Network có dạng:

`y = XW + b`

Trong code:

`output = X @ W + b`

Nên:

`matrix multiplication + broadcasting`

sẽ xuất hiện liên tục.

# **Task 4 — Hiểu axis**

**Cho:**

```
scores = np.array([    
  [8, 7, 9],    
  [6, 8, 7],    
  [9, 9, 8]
])
```
Có thể hiểu:
```
          Math   English   AI
Student1    8       7      9
Student2    6       8      7
Student3    9       9      8
```

**Không dùng axis**

`np.mean(scores, axis=1)`

NumPy tính trung bình toàn bộ 9 giá trị

**axis = 0**

`np.mean(scores, axis=0)`

```
Output:
[7.666... 8.0 8.0]
```
**Hiểu là: đi theo chiều dọc, gộp các row lại**

Kết quả là trung bình từng column.

**Tức là**

```
Math average
English average
AI average
```

**axis = 1**

`np.mean(scores, axis=1)`
```
Output đại loại:
[8.0 7.0 8.666...]
```
**Hiểu là: tính theo từng row**

```
Tức là:
Student 1 average
Student 2 average
Student 3 average
```

**Mẹo nhớ**

**Với matrix:**
```
axis=0
→ collapse rows
→ còn columns
```
```
axis=1
→ collapse columns
→ còn rows
```

**Hoặc trong ví dụ student:**
```
axis=0 → theo môn

axis=1 → theo student
```

# **Task 5 — Statistics**

In [ ]:
scores = ([8, 7, 9, 6])

# Sum
print(np.sum(scores))

# Mean
print(np.mean(scores))

# Min
print(np.min(scores))

# Max
print(np.max(scores))

# Standard Deviation: độ phân tán của dữ liệu quanh mean
print(np.std(scores))

30
7.5
6
9
1.118033988749895


**argmax() và argmin()**

In [ ]:
# Ngoài giá trị lớn nhất, đôi khi ta cần index
scores = np.array([7, 9, 6, 8])

print(np.max(scores))

print(np.argmax(scores))

# Tương tự
print(np.min(scores))
print(np.argmin(scores))

9
1
6
2


# **Task 6 — Coding Practice**

In [ ]:
# Ex 1

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

print(a ** 2)

print(np.dot(a, b))
print(a @ b) # Chỉ là cách viết khác của np.dot()

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
32
32


In [ ]:
# Ex 2

A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])

print(A * B)

print(A @ B)

# A @ B khác A * B vì:
# A * B là element-wise operations
# A @ B là matrix multiplication

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
# Ex 3

scores = np.array([
    [8, 7, 9],
    [6, 8, 7],
    [9, 9, 8]
])

print(np.mean(scores))
print(np.mean(scores, axis=0))
print(np.mean(scores, axis=1))

print(np.sum(scores))
print(np.min(scores))
print(np.max(scores))
print(np.std(scores))

print(np.max(scores, axis = 1))
print(np.min(scores, axis = 0))

7.888888888888889
[7.66666667 8.         8.        ]
[8.         7.         8.66666667]
71
6
9
0.9938079899999066
[9 8 9]
[6 7 7]


In [ ]:
# Ex 4

scores = np.array([7.5, 8.0, 9.0, 6.5, 8.5])

print(np.argmax(scores))
print(np.argmin(scores))

2
3


In [ ]:
# Ex 5
X = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

W = np.array([
    [0.5],
    [1.0]
])

print(X @ W) # (3, 2) x (2, 1) = (3, 1)

[[2.5]
 [5.5]
 [8.5]]


# **Task 7 — Mini Challenge**

# **Student Score Analysis with NumPy**

In [ ]:
scores = np.array([
    [8.5, 7.0, 9.0],
    [6.0, 8.0, 7.5],
    [9.0, 9.5, 8.5],
    [5.5, 6.0, 7.0]
])

# Require 1: Average toàn bộ
overall_average = np.mean(scores)
print(overall_average)

# Require 2: Average từng Student
print(np.mean(scores, axis = 1))

# Require 3: Average từng môn
print(np.mean(scores, axis = 0))

# Require 4: Highest score
print(np.max(scores))

# Require 5: Lowest score
print(np.min(scores))

# Require 6: Highest score từng student
print(np.max(scores, axis = 1))

# Require 7: Standard deviation từng môn
print(np.std(scores, axis = 0)) # môn nào có std lớn hơn nghĩa là điểm giữa các student phân tán hơn

# Require 8: Best student
average_students = np.mean(scores, axis = 1)
print(np.argmax(average_students) + 1)

# Require 9: Best subject
average_subjects = np.mean(scores, axis = 0)
print(np.argmax(average_subjects) + 1)

# Require 10: Weighted Score

weights = np.array([0.3, 0.2, 0.5])
weighted_scores = scores @ weights
print(weighted_scores)

# Optional Challenge
print(np.argmax(weighted_scores) + 1)

7.625
[8.16666667 7.16666667 9.         6.16666667]
[7.25  7.625 8.   ]
9.5
5.5
[9.  8.  9.5 7. ]
[1.52069063 1.29301005 0.79056942]
3
3
[8.45 7.15 8.85 6.35]
3
