<a href="https://colab.research.google.com/github/PhatDiaz/ai-engineer-roadmap/blob/main/day04_numpy_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Task 1 — NumPy Array**

In [ ]:
# Import:

import numpy as np

# Tạo array
numbers = np.array([1, 2, 3, 4, 5])
print(numbers)


[1 2 3 4 5]


**Python List vs NumPy Array**

In [ ]:
# Python list
numbers = [1, 2, 3, 4, 5]

# NumPy Array
numbers_array = np.array([1, 2, 3, 4, 5])

**Điểm quan trọng:**

```
Python List
→ dữ liệu tổng quát

NumPy Array
→ tính toán số học nhanh, vector/matrix
```

In [ ]:
# Ví dụ
numbers = np.array([1, 2, 3])
print(numbers * 2)

# Trong khi
numbers = [1, 2, 3]
print(numbers * 2)

[2 4 6]
[1, 2, 3, 1, 2, 3]


**1D ARRAY**

In [ ]:
a = np.array([10, 20, 30, 40])
print(a)

[10 20 30 40]


**2D ARRAY**

In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(matrix)

# Hay:  2 rows
#       3 columns

[[1 2 3]
 [4 5 6]]


**3D ARRAY**

In [ ]:
x = np.array([
  [
      [1, 2],
      [3, 4]
  ],
  [
      [5, 6],
      [7, 8]
  ]
])

print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# **Task 2 — shape, ndim, size, dtype**

In [ ]:
# Cho:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Shape
print(matrix.shape) # nghĩa là 2 rows, 3 columns

# ndim
print(matrix.ndim)  # nghĩa là không gian 2 chiều

# size
print(matrix.size)  # tổng cộng 2 x 3 = 6 phần tử

# dtype
print(matrix.dtype) # có thể ra int64 hoặc int32 tùy môi trường


# Tự chỉ định type
scores = np.array(
    [8, 9, 7],
    dtype = float
)
print(scores)

(2, 3)
2
6
int64
[8. 9. 7.]


**Cần phân biệt:**
```
shape -> kích thước từng chiều

ndim -> có bao nhiêu chiều

size -> tổng số phần tử

dtype -> kiểu dữ liệu
```

**Ví dụ:**


```
x = np.array([
  [1, 2],
  [3, 4],
  [5, 6]
])
```
thì

```
shape = (3, 2)
ndim  = 2
size  = 6
```





# **Task 3 — Indexing**

**1D Array**

In [ ]:
numbers = np.array([10, 20, 30, 40, 50])

print(numbers[0])
print(numbers[-1])

10
50


**2D Indexing**

In [ ]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(matrix[0, 0])
print(matrix[0, 2])

10
30


# **Task 4 — Slicing**

In [ ]:
# Giống Day 1
numbers = np.array([10, 20, 30, 40, 50])

print(numbers[1:4])

[20 30 40]


**Slicing 2D**

In [ ]:
# Cho:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Lấy row đầu
print(matrix[0, :])   # : nghĩa là lấy tất cả

# Lấy column đầu
print(matrix[:, 0])

# Lấy column thứ 2
print(matrix[:, 1])

# Lấy 2 hàng đầu + 2 cột đầu
print(matrix[0:2, 0:2])

# Hãy đọc:
# rows 0 -> 1
# columns 0 -> 1

[1 2 3]
[1 4 7]
[2 5 8]
[[1 2]
 [4 5]]


```
matrix[:, 1]
```
nghĩa là:

```
tất cả rows
column 1
```




# **Task 5 — Reshape**

In [ ]:
# Cho:
numbers = np.array([
    1, 2, 3,
    4, 5, 6
])

print(numbers.shape)

# Ta muốn 2 rows, 3 columns thì dùng:
matrix = numbers.reshape(2, 3)
print(matrix)

# 3 rows, 2 columns
print(numbers.reshape(3, 2))

(6,)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


**Quy tắc cực kỳ quan trọng**

Số phần tử phải giữ nguyên

Array có:

`6 elements`

nên:
```
reshape(2, 3) ✅
reshape(3, 2) ✅
reshape(1, 6) ✅
reshape(6, 1) ✅
```
nhưng:

```
reshape(4, 2) ❌
```
vì:

```
4 × 2 = 8
```

**Flatten**

In [ ]:
# Từ
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

matrix.flatten()

array([1, 2, 3, 4, 5, 6])

# **Task 6 — Broadcasting**

Ví dụ:


```
numbers = np.array([
    1, 2, 3
])
numbers + 10
```
->
`[11 12 13]`

NumPy hiểu:

```
[1 2 3]
+
10
```
như:

```
[1 2 3]
+
[10 10 10]
```
**Đây chính là broadcasting**

**Nhân scalar**

```
numbers * 2 -> [2, 4, 6]
```

**Broadcasting với matrix**

In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

bias = np.array([
    10, 20, 30
])

print(matrix + bias)

# NumPy tự broadcast [10, 20, 30] cho từng row

[[11 22 33]
 [14 25 36]]


# **Task 7 — Coding Practice**

In [ ]:
# Ex 1

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[1 2 3 4 5]
(5,)
1
5
int64


In [ ]:
# Ex 2

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix.shape)

(2, 3)


In [ ]:
# Ex 3

arr = np.array([10, 20, 30, 40, 50])

print(arr[2])
print(arr[-1])

30
50


In [ ]:
# Ex 4

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix[1, 1])
print(matrix[1, :])
print(matrix[:, 1])
print(matrix[0:2, 0:2])

5
[4 5 6]
[2 5 8]
[[1 2]
 [4 5]]


In [ ]:
# Ex 5

arr = np.array([1, 2, 3, 4, 5, 6])

matrix1 = arr.reshape(2, 3)
matrix2 = arr.reshape(3, 2)
print(matrix1.shape)
print(matrix2.shape)

(2, 3)
(3, 2)


In [ ]:
# Ex 6

matrix = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(matrix.flatten())

[1 2 3 4 5 6]


In [ ]:
# Ex 7

arr = np.array([1, 2, 3, 4])
print(arr + 10)
print(arr * 5)

[11 12 13 14]
[ 5 10 15 20]


In [ ]:
# Ex 8

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

bias = np.array([10, 20, 30])

print(matrix + bias)
# Phép tính trên chạy được là nhờ cơ chế broadcasting trong python

[[11 22 33]
 [14 25 36]]


In [ ]:
# Ex 9
arr = np.arange(1, 13)
print(arr.reshape(3, 4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# **Task 8 — Mini Challenge**

In [ ]:
scores = np.array([
    [8.5, 7.0, 9.0],
    [6.0, 8.0, 7.5],
    [9.0, 9.5, 8.5],
    [5.5, 6.0, 7.0]
])

# Requirement 1
print(scores.shape)
print(scores.ndim)
print(scores.size)

# Requirement 2
print(scores[1, :])

# Requirement 3
print(scores[:, 2])

# Requirement 4
print(scores[2, 1])

# Requirement 5
bonus = np.array([0.5, 0.5, 0.5])
new_scores = scores + bonus
print(new_scores)

# Requirement 6
flat_scores = scores.flatten()
print(flat_scores)

# Requirement 7
student_ids = np.arange(1, 5)
print(student_ids)

(4, 3)
2
12
[6.  8.  7.5]
[9.  7.5 8.5 7. ]
9.5
[[ 9.   7.5  9.5]
 [ 6.5  8.5  8. ]
 [ 9.5 10.   9. ]
 [ 6.   6.5  7.5]]
[8.5 7.  9.  6.  8.  7.5 9.  9.5 8.5 5.5 6.  7. ]
[1 2 3 4]


np.arange(1, 5)
→ trả về NumPy ndarray
→ [1 2 3 4]

range(1, 5)
→ trả về Python range object
→ thường dùng cho loop

Cả hai đều không lấy stop = 5.